E-Commerce.PL/Controllers/HomeController.cs
using E_Commerce.DAL.Entity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_Commerce.PL.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

E-Commerce.PL/Controllers/ProductController.cs
using AutoMapper;
using E_Commerce.BLL.Interface;
using E_Commerce.BLL.Model;
using E_Commerce.BLL.Reposatiry;
using E_Commerce.DAL.Entity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_Commerce.PL.Controllers
{
    public class ProductController : Controller
    {
        IProduct product;
        private readonly IMapper mapper;

        public ProductController(IProduct instance,IMapper mapper)
        {
            product = instance;
            this.mapper = mapper;
        }
        public IActionResult Index(ProductVM model)
        {
           var data = product.Get();
          var Model = mapper.Map<IEnumerable<ProductVM>>(data);
            
            return View(Model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ProductVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                 var Model=   mapper.Map<Product>(model);
                    product.Create(Model);
                    return RedirectToAction("Index");

                }   
                
              return View(model);
            }
            catch (Exception)
            {

                return View(model);
            }

         

        }
        public IActionResult Details(int Id)
        {
            try
            {
                var data = product.GetById(Id);
                var Model = mapper.Map<ProductVM>(data);
                return View(Model);
            }
            catch (Exception)
            {

                return RedirectToAction("Index");
            }


        }
        [HttpGet]
        public IActionResult Update(int Id) 
        {
            var data = product.GetById(Id);
            var Model = mapper.Map<ProductVM>(data);
            return View(Model);
        }
        [HttpPost ]
        public IActionResult Update(ProductVM model) 
        {
            try
            {
            if (ModelState.IsValid) 
            {
                    var Model = mapper.Map<Product>(model);
                    product.Edit(Model);
                    return RedirectToAction("Index");
            }  
            return View(model);  
            }
            catch (Exception)
            {
                return View(model);
            }
        }
        [HttpGet]
        public IActionResult Delete(int Id)
        {
            var data = product.GetById(Id);
            var Model = mapper.Map<ProductVM>(data);
            return View(Model);
        }
        [HttpPost]
        public IActionResult Delete(ProductVM model)  
        {
            try
            {
                var Model = mapper.Map<Product>(model);
                product.Delete( Model);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                return View();
            }
           
        }
    }
}

E-Commerce.PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

E-Commerce.PL/Views/Product/Create.cshtml
@model E_Commerce.BLL.Model.ProductVM
@{
    ViewData["Title"] = "Create";
}


<form  asp-controller="Product" asp-action="Create">
    <div class="form-group row">
        <label asp-for="Name" class="col-sm-12 col-md-2 col-form-label">Name</label>
        <div class="col-sm-12 col-md-10 ">
            <input type="text" asp-for="Name" class="form-control">
            <span asp-validation-for="Name" class="alert-danger"></span>
        </div>
    </div>
        <div class="form-group row">
            <label asp-for="Price" class="col-sm-12 col-md-2 col-form-label">Price</label>
            <div class="col-sm-12 col-md-10 ">
                <input type="number" asp-for="Price" class="form-control">
                <span asp-validation-for="Price" class="alert-danger"></span>
            </div>

        </div>  
        <div class="form-group row">

            <label asp-for="Color" class="col-sm-12 col-md-2 col-form-label">Color</label>
            <div class="col-sm-12 col-md-10 ">
                <input type="text" asp-for="Color" class="form-control">
                <span asp-validation-for="Color" class="alert-danger"></span>
            </div>
        </div>   
        <div class="form-group row">
            <label asp-for="Size" class="col-sm-12 col-md-2 col-form-label">Size</label>
            <div class="col-sm-12 col-md-10 ">
                <input type="text" asp-for="Size" class="form-control">
                <span asp-validation-for="Size" class="alert-danger"></span>
            </div>
        </div> 
        <div class="form-group row">
            <label asp-for="Quantity" class="col-sm-12 col-md-2 col-form-label">Quantity</label>
            <div class="col-sm-12 col-md-10 ">
                <input type="number" asp-for="Quantity" class="form-control">
                <span asp-validation-for="Quantity" class="alert-danger"></span>
            </div>

        </div>  
        <div class="form-group row">

            <label asp-for="ProductUser" class="col-sm-12 col-md-2 col-form-label">ProductUser</label>
            <div class="col-sm-12 col-md-10 ">
                <input type="text" asp-for="ProductUser" class="form-control">
                <span asp-validation-for="ProductUser" class="alert-danger"></span>
            </div>

        </div>   
        <div class="form-group row">
            <label asp-for="Describtion" class="col-sm-12 col-md-2 col-form-label">Describtion</label>
            <div class="col-sm-12 col-md-10 ">
                <input type="text" asp-for="Describtion" class="form-control">
                <span asp-validation-for="Describtion" class="alert-danger"></span>
            </div>

        </div>   
            <input type="submit" class="btn btn-primary" value="Add">
        
</form>
<script src="~/jquery/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

E-Commerce.PL/Views/Product/Delete.cshtml
@model E_Commerce.BLL.Model.ProductVM
@{
    ViewData["Title"] = "Delete";
}


<form asp-controller="Product" asp-action="Delete">
<input type="hidden" asp-for="ID" class="form-control" readonly>
<br>
<input type="text" asp-for="Name" class="form-control" readonly>
<br>
<input type="text" asp-for="Price" class="form-control" readonly>
<br>
<input type="text" asp-for="Color" class="form-control" readonly>
<br>
<input type="text" asp-for="Quantity" class="form-control" readonly>
<br>
<input type="text" asp-for="Size" class="form-control" readonly>
<br>
<input type="text" asp-for="ProductUser" class="form-control" readonly>
<br>
<input type="text" asp-for="Describtion" class="form-control" readonly>
<br>
    <input type="submit" value="Delete" class="btn btn-primary">
</form>

E-Commerce.PL/Views/Product/Details.cshtml
@model E_Commerce.BLL.Model.ProductVM
@{
    ViewData["Title"] = "Details";
}

        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div class="title">
                            <h4>Product Detail</h4>
                        </div>
                        <nav aria-label="breadcrumb" role="navigation">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a asp-controller="Product" asp-action="Index">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Product Detail</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="product-wrap">
                <div class="product-detail-wrap mb-30">
                    <div class="row">
                        <div class="col-lg-6 col-md-12 col-sm-12">
                            <div class="product-slider slider-arrow">
                                <div class="product-slide">
                                    <img src="~/vendors/images/product-@(Model.ID).jpg" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-12 col-sm-12">
                            <div class="product-detail-desc pd-20 card-box height-100-p">
                                <h4 class="mb-20 pt-20">@Model.Name</h4>
                                <p>@Model.Describtion</p>
                                <div class="price">
                                    <ins> Price : @Model.Price$</ins>
                                    <br>
                                    <br>
                                    <ins> Color : @Model.Color</ins>
                                </div>
                                <div class="mx-w-150">
                                    <div class="form-group">
                                        <label class="text-blue">Quantity</label>
                                        <input id="demo3_22" type="text" value="@Model.Quantity" name="demo3_22">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6 col-6">
                                        <a href="#" class="btn btn-primary btn-block">Add To Cart</a>
                                    </div>
                                    <div class="col-md-6 col-6">
                                        <a href="#" class="btn btn-outline-primary btn-block">Buy Now</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <h4 class="mb-30">Recent Product</h4>
                <div class="product-list">
                    <ul class="row">
                        <li class="col-lg-4 col-md-6 col-sm-12">
                            <div class="product-box">
                                <div class="producct-img"><img src="~/vendors/images/product-img1.jpg" alt=""></div>
                                <div class="product-caption">
                                    <h4><a href="#">@Model.Name Black</a></h4>
                                    <div class="price">
                                        <del>$55.5</del><ins>$49.5</ins>
                                    </div>
                                    <a href="#" class="btn btn-outline-primary">Read More</a>
                                </div>
                            </div>
                        </li>
                        <li class="col-lg-4 col-md-6 col-sm-12">
                            <div class="product-box">
                                <div class="producct-img"><img src="~/vendors/images/product-img2.jpg" alt=""></div>
                                <div class="product-caption">
                                    <h4><a asp-controller="Product" asp-action="Index">@Model.Name White</a></h4>
                                    <div class="price">
                                        <del>$75.5</del><ins>$50</ins>
                                    </div>
                                    <a href="#" class="btn btn-outline-primary">Add To Cart</a>
                                </div>
                            </div>
                        </li>
                        <li class="col-lg-4 col-md-6 col-sm-12">
                            <div class="product-box">
                                <div class="producct-img"><img src="~/vendors/images/product-img3.jpg" alt=""></div>
                                <div class="product-caption">
                                    <h4><a href="#">Contrast Lace-Up Sneakers</a></h4>
                                    <div class="price">
                                        <ins>$80</ins>
                                    </div>
                                    <a href="#" class="btn btn-outline-primary">Add To Cart</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

E-Commerce.PL/Views/Product/Index.cshtml
@model IEnumerable<E_Commerce.BLL.Model.ProductVM>
@{
    ViewData["Title"] = "Index";
}

<a asp-controller="Product" asp-action="Create" class="btn btn-primary">Add New Product</a>

<div class="card-box mb-30">
        <h2 class="h4 pd-20">Best Selling Products</h2>
        <table class="data-table table nowrap">
            <thead>
                <tr>
                    <th class="table-plus datatable-nosort">Product</th>
                    <th> Name  </th>
                    <th>Price</th>
                    <th>Color</th>
                    <th>Size</th>
                    <th>Quntity</th>
                    <th class="datatable-nosort">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {

                    <tr>
                        <td class="table-plus">
                            <img src="~/vendors/images/product-@(item.ID).jpg" width="80" height="80" alt="">
                        </td>
                        <td>@item.Name</td>
                        <td>@item.Price</td>
                        <td>@item.Color</td>
                        <td>@item.Size</td>
                        <td>@item.Quantity</td>
                        <td>
                            <div class="dropdown">
                                <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                                    <i class="dw dw-more"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                                    <a class="dropdown-item" asp-controller="Product" asp-action="Details" asp-route-Id="@item.ID"><i class="dw dw-eye"></i> View</a>
                                    <a class="dropdown-item" asp-controller="Product" asp-action="Update" asp-route-Id="@item.ID"><i class="dw dw-edit2"></i> Edit</a>
                                    <a class="dropdown-item" asp-controller="Product" asp-action="Delete" asp-route-Id="@item.ID"><i class="dw dw-delete-3"></i> Delete</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>

E-Commerce.PL/Views/Product/Update.cshtml
@model E_Commerce.BLL.Model.ProductVM
@{
    ViewData["Title"] = "Update";
}


<form asp-controller="Product" asp-action="Update" class="form-group">
    <input type="hidden" asp-for="ID">
    <label asp-for="Name">Name</label>
    <input type="text" asp-for="Name" class="form-control">
    <span asp-validation-for="Name" class="text-danger"></span>
    <br>
    <label asp-for="Price">Price</label>
    <input type="text" asp-for="Price" class="form-control">
    <span asp-validation-for="Price" class="text-danger"></span>
    <br>
    <label asp-for="Color">Color</label>
    <input type="text" asp-for="Color" class="form-control">
    <span asp-validation-for="Color" class="text-danger"></span>
    <br>
    <label asp-for="Quantity">Quantity</label>
    <input type="text" asp-for="Quantity" class="form-control">
    <span asp-validation-for="Quantity" class="text-danger"></span>
    <br>
    <label asp-for="Size">Size</label>
    <input type="text" asp-for="Size" class="form-control">
    <span asp-validation-for="Size" class="text-danger"></span>
    <br>
    <label asp-for="ProductUser">ProductUser</label>
    <input type="text" asp-for="ProductUser" class="form-control">
    <span asp-validation-for="ProductUser" class="text-danger"></span>
    <br>
    <label asp-for="Describtion">Describtio</label>
    <input type="text" asp-for="Describtion" class="form-control">
    <span asp-validation-for="Describtion" class="text-danger"></span>
    <br>
    <input type="submit" value="Save Change" class="btn btn-primary">
</form>
<script src="~/jquery/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>